apiVersion: v1
kind: Service
metadata:
  name: composite-cancel-booking
  namespace: default
spec:
  selector:
    app: composite-cancel-booking
  ports:
    - port: 6002
      targetPort: 6002
  type: ClusterIP
