apiVersion: v1
kind: Service
metadata:
  name: composite-report-issue
  namespace: default
spec:
  selector:
    app: composite-report-issue
  ports:
    - port: 6003
      targetPort: 6003
  type: ClusterIP
