apiVersion: v1
kind: Service
metadata:
  name: twilio-wrapper-http
  namespace: default
spec:
  selector:
    app: twilio-wrapper-http
  ports:
    - port: 6203
      targetPort: 6203
  type: ClusterIP
