apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
        - name: pricing-service
          image: esd-pricing-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5005
          livenessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
