apiVersion: v1
kind: Service
metadata:
  name: composite-book-car
  namespace: default
spec:
  selector:
    app: composite-book-car
  ports:
    - port: 6001
      targetPort: 6001
  type: ClusterIP
