apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: esd-vehicle-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: vehicle-service-config
                  key: FIREBASE_PROJECT_ID
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/firebase-service-account.json
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
          volumeMounts:
            - name: firebase-sa
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: firebase-sa
          secret:
            secretName: firebase-sa
