apiVersion: v1
kind: ConfigMap
metadata:
  name: composite-resolve-issue-config
  namespace: default
data:
  FIREBASE_PROJECT_ID: "esd-rental-car"
  PORT: "6004"
  REPORT_SERVICE_HOST: "report-service:5004"
  # NOTE: TWILIO_WRAPPER_HOST comes from common-config in Deployment (not here)
