apiVersion: v1
kind: Service
metadata:
  name: composite-resolve-issue
  namespace: default
spec:
  selector:
    app: composite-resolve-issue
  ports:
    - port: 6004
      targetPort: 6004
  type: ClusterIP
